# base image
FROM ubuntu:20.04

#input GitHub runner version argument
ENV DEBIAN_FRONTEND=noninteractive

# update the base packages + add a non-sudo user
RUN apt-get update -y && apt-get upgrade -y && useradd -m docker

RUN apt-get install sudo -y

RUN usermod -aG sudo docker

RUN echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# install the packages and dependencies along with jq so we can parse JSON (add additional packages as necessary)
RUN apt-get install -y --no-install-recommends \
    curl nodejs wget unzip vim git azure-cli jq build-essential libssl-dev libffi-dev python3 python3-venv python3-dev python3-pip

RUN apt-get install -y gconf-service libgbm-dev \
		libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 \
		libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
		libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

# cd into the user directory, download and unzip the github actions runner
RUN cd /home/docker && mkdir temp && cd temp \
    && curl -O -L https://github.com/actions/runner/releases/download/v2.296.2/actions-runner-linux-x64-2.296.2.tar.gz \
    && tar xzf ./actions-runner-linux-x64-2.296.2.tar.gz

# install some additional dependencies
RUN chown -R docker ~docker && /home/docker/temp/bin/installdependencies.sh

# RUN DESPUES
RUN curl -s https://deb.nodesource.com/setup_16.x | bash

RUN apt install nodejs -y

RUN npm install -g pm2

ADD scripts/start.sh start.sh

RUN chmod +x start.sh

USER docker

ENTRYPOINT ["./start.sh"]